version: '2'
services:
    web:
      image: nginx
      links:
        - app1
        - app2
      ports:
        - 80:80
      volumes:
        - ./conf.d:/etc/nginx/conf.d

    app1:
      image: php:7.3.4-fpm-alpine3.9
      volumes:
        - ./main-app:/srv/app

    app2:
      image: php:7.3.4-fpm-alpine3.9
      volumes:
        - ./sub-app:/srv/app
